# Generated by Django 4.0.1 on 2023-06-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='room',
        ),
    ]
