# Generated by Django 4.0.1 on 2023-06-27 18:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_room_photo_roomusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sended', models.DateTimeField(default=datetime.datetime(2023, 6, 27, 20, 33, 36, 355757))),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomUsers',
        ),
    ]
