# Generated by Django 4.0.1 on 2023-06-27 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_roomlogs_data_sended_roomlogs_data_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlogs',
            name='data_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 20, 42, 48, 22969)),
        ),
        migrations.AlterField(
            model_name='roomlogs',
            name='data_left',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
